### PR TITLE
Preserve crossOrigin attribute

### PR DESCRIPTION
**Pull request by baoshan**
For `crossorigin` images, the cache image should have the same `crossorigin` attribute.

This ensures the browser sending exactly the same request as requesting the original image, which has performance benefits as well as better CORS support.

### CODE REVIEW

**Comment by desandro** [comment]
Thanks for this contribution. I'll have to take a look

**Comment by baoshan** [comment]
Thanks. :)

**Comment by baoshan** [comment]
This PR solves #109 I believe. Have a look. :)

**Comment by denniscollective** [comment]
We've been having crazy issues in our app that we think this might be the cause of. Thanks for tracking it down @baoshan. Since #109 was closed because "no one chimed in", I'm chiming in. this is really important.

Thanks <3 <3 <3

**Comment by raindrift** [comment]
+1

This is required when using imagesloaded to determine when to run something that uses a canvas with the image (like colorthief) with cross-domain images. The issue is super hard to track down, though, because it only occurs sometimes in some browsers. I think you'd hear about it more, but CORS is complicated and people probably assume some other part of their configuration is messed up.

**Comment by wad3inthewater** [comment]
I also ran into this issue, thanks @baoshan

**Comment by wgiddens** [comment]
+1

**Comment by polco-gelato** [comment]
+1 i get the issue with the latest Safari.

**Comment by desandro** [comment]
Thanks again for this contribution. I've added this feature and it will be a part of the v5 release

**Pull request closed without merging**
