### PR TITLE
Add support for Composer

### PR DESCRIPTION
**Pull request by lucastockmann**
For future releases it was great you could add this composer.json and add the package to packagist.org :)

### CODE REVIEW

**Comment by desandro** [comment]
Thanks for the contribution. Please **+1** or subscribe to this issue if you would like to see Composer support added.

**Comment by albertvolkman** [comment]
This should absolutely be added...

**Comment by desandro** [comment]
Closing this feature request. It hasn't gotten enough interest over the past 7 seven months.

**Comment by desandro** [comment]
I've relented. Composer support added in #224

**Pull request closed without merging**
