### PR TITLE
require jQuery optionally

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by desandro** [comment]
Thanks for this contribution. I'm curious what benefits you see to try loading in jQuery. I'd prefer not to use a try catch

**Comment by graingert** [comment]
This try except is specifically supported by webpack

**Comment by desandro** [comment]
Which PR should we look at? This one or #221

What errors do you experience using the [Webpack instructions](http://imagesloaded.desandro.com/#webpack)?

**Comment by graingert** [comment]
@desandro they build on each other. #221 is just a straight bugfix

**Comment by graingert** [comment]
@desandro I get an attribute error .jqDeffered https://github.com/desandro/imagesloaded/blob/master/imagesloaded.js#L104 because it's not set at the correct point in time.

**Comment by desandro** [comment]
`$` may not be set initially, but does get set in `.makeJQueryPlugin()`. Looks like instructions had a typo (`var jQuery` should be `var $`). Try this:

``` js
// main.js
var imagesLoaded = require('imagesLoaded');
var $ = require('jquery');

// provide jQuery argument
imagesLoaded.makeJQueryPlugin( $ );
// now use .imagesLoaded() jQuery plugin
$('#container').imagesLoaded( function() {...});
```

**Comment by desandro** [comment]
Updated README in SHA: 154ea174d10db200346a2b3503271a4136aaf362

**Pull request closed without merging**
